{
 "title": " Database Exporter ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "label_values(cpu)" } },
   { "name": "query1", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  {
   "title": "cpu time usage total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "received bytes from clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_bytes_received",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opened tables per 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_opened_tables[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "speed of bytes send",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_sent[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query processing speed (QPS)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "runtime in seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_global_status_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_max_user_connections\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}