{
 "title": "Custom_exporter Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "country",
    "query": {
     "query": "label_values(weather_windspeed_kmh{country=\"Kazakhstan\"},country)"
    }
   },
   {
    "name": "city",
    "label": "city",
    "query": {
     "query": "label_values(weather_temperature_celsius, city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "maximum windspeed 6h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(weather_windspeed_kmh{city=\"Astana\"}[6h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average temperature over 60 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius{city=\"Astana\"}[60m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "minimum temperature last 6 h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "min_over_time(weather_temperature_celsius{city=\"Astana\"}[6h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"Astana\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "maximum of active users 1h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(simulated_active_users[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average wind speed kmh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by (country)(weather_windspeed_kmh)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage mb",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC / ETH",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(crypto_eth_usd / crypto_btc_usd) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "custom_exporter_requests 5m",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(custom_exporter_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum of simulated users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "sum(simulated_active_users)", "legendFormat": "__auto" }
   ]
  }
 ]
}